services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - chroma
      - ollama
    ports:
      - "8000:8000"

  chroma:
    image: chromadb/chroma:latest    
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/data

  ollama:
    image: ollama/ollama:0.6.3    
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postgres:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    volumes:
      - psql-data:/var/opt/psql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: starbursts

volumes:
  chroma_data:
  ollama_data:
  localai_data:
  psql-data: